### PR TITLE
Slick 3.1

### PR DESCRIPTION
**Pull request by Fokko**
Hi guys,

First of all, thanks for the awesome work on Slick. Like it a lot. 

I've updated the Slick 3.1 branch to the latest version and added the Typesafe repo to the SBT resolvers to get everything working again.

Cheers, Fokko.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @Fokko,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by cvogt** [comment]
Thx :)!

**Comment by cvogt** [comment]
LGTM. Can be merged

**Comment by Fokko** [comment]
Thanks. I've signed the Typesafe CLA.

**Pull request merged**
